### ISSUE TITLE
html/pdf 的托管位置

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#100]
github 上访问太慢了。

都放到 book.haoduoshipin.com/tlcl 之下

**Comment by happypeter** [comment]
http://billie66.github.io/TLCL 上发声明，指向新位置。

pdf 中相应的链接也要改正。

**Comment by Pines-Cheng** [comment]
> http://billie66.github.io/TLCL 上发声明，指向新位置。
> 
> pdf 中相应的链接也要改正。

test

**Comment by billie66** [comment]
这两天 github 访问是比较慢，翻墙之后还可以
