### ISSUE TITLE
26 章启动一个项目 接近结尾处多出来两个 “\”

### ISSUE THREAD

**Issue by chouch0u** [billie66/TLCL#116]
26 章启动一个项目 原文：

> 如果我们把重定向操作符从 “<\<” 改为 “<\<-”，shell 会忽略在此 here document 中开头的 tab 字符。 这就能缩进一个 here document，从而提高脚本的可读性：

`<\<` 和 `<\<-` 应该更改为 `<<`和`<<-`

**Comment by chouch0u** [comment]
我又看了一下 git 的原文没有这个问题。但是在 gitbook 上有这个问题。https://billie66.gitbooks.io/tlcl-cn/content/chap25/starting-a-project.html

**Comment by billie66** [comment]
嗯，markdown 的语法中 `\` 反斜杠可以转义一些特殊字符，但这里没有必要转义。

gitbook 的文档需要更新了，等有时间我会处理一下
