### ISSUE TITLE
错别字：chap05 表5-2 [:upper] 缺少一个冒号(:)

### ISSUE THREAD

**Issue by ksco** [billie66/TLCL#128]
| 字符类 | 意义 |
| --- | --- |
| [:upper] -> **[:upper:]** | 匹配任意一个大写字母 |

**Comment by billie66** [comment]
@ksco 谢谢反馈，已经改正

**Comment by leavesster** [comment]
### gitbook中版本比较旧，能否也更新下？

使用的mobi版本，在kindle上观看时，发现同样的问题。

紧接着下面
表5-3：通配符范例 

|模式 | 匹配对象|
|--|--|
|b.txt|以"b"开头，中间有零个或多个字符，并以".txt"结尾的文件|

b.txt应该是b*.txt。在中英文版中也是好的。

看了一下，中英版是好的，似乎是因为gitbook上的版本过旧的缘故。
标记是中文版 (PDF-2014-9-26)，mobi版本只有中文，应该也是这个版本，能否对应的更新一下。

谢谢。

**Comment by happypeter** [comment]
本项目是非盈利的，目前运行在非常有限的人力资源之上。我的建议还是全力维护 html 版本，其他格式的放弃维护。

当然，也欢迎其他参与者进来维护。

**Comment by leavesster** [comment]
抱歉，后面才看到gitbook的已经不再维护了。

gitbook似乎和github不通用。
如果我这边自行上传一份更新，有什么办法可以让你这边连接到吗？
不是很了解gitbook的运作方式，似乎他是单账号的，没有github这种协作。

**Comment by happypeter** [comment]
@leavesster 您可以自行做一份，然后 TLCL 网站首页上我们给出一个链接指向您的那边。

**Comment by leavesster** [comment]
@happypeter 晚上尝试了一下，完全不了解的情况下，还真是颇费周折啊，辛苦两位了呢。我用python做了SUMMARY.md。然后折腾半天做好了新的mobi，但是核对的时候发现中文版mobi，此处还是不对。翻了下文件，是因为中文版md文件本身没有更新的原因。

今天挺晚了，等我明天用仓库中获取中文的ruby脚本跑一边，然后再做一个新的吧。到时候两位看看是否合适吧。
: )

**Comment by happypeter** [comment]
@leavesster 期待
