### ISSUE TITLE
A mistake in chapter 04

### ISSUE THREAD

**Issue by timehacker** [billie66/TLCL#14]
Table 4-1: Common ls Options
原文：
-a  List all files, even those with names that begin with a period, which are normally not listed(i.e.,hidden).
翻译：
列出所有文件名，包括以圆点开头的文件名，一般不会列出隐藏文件名。
更正：
列出所有文件，包括以圆点开头的默认隐藏的文件。

**Comment by billie66** [comment]
这是一个错误，我会修改的，谢谢参与。

**Comment by suyuxp** [comment]
我也来凑合一个：

```
-a  参数会列出所有文件，甚至包括那些以圆点开头的默认隐藏文件。
```

**Comment by happypeter** [comment]
@suyuxp 多谢
