### ISSUE TITLE
第14章 终端颜色序列 背景色不对应

### ISSUE THREAD

**Issue by lwj786** [billie66/TLCL#147]
原文为
***\033[0;40m Blue     \033[1;44m Black***
![2017-01-10 16-21-02](https://cloud.githubusercontent.com/assets/17615532/21798957/1898a25e-d752-11e6-8260-39c244bc1fff.png)
实验：
![2017-01-10 16-19-41](https://cloud.githubusercontent.com/assets/17615532/21799037/712e45fe-d752-11e6-8b68-16d25fd94c2f.png)
应该是原文有误

**Comment by happypeter** [comment]
感谢，回头会统一处理。
