### ISSUE TITLE
第二十一章：纯中文版，定义字段部分文本残缺

### ISSUE THREAD

**Issue by Steven1677** [billie66/TLCL#149]
> 这个 k 选项非常有趣，而且还有很多特点，但是首先我们需要讲讲 sort 程序怎样来定义字段。 让我们考虑一个非常简单的文本文件，只有一行包含作者名字的文本。
> 
> William      Shotts
> 默认情况下，sort 程序把此行看作有两个字段。第一个字段包含字符：
> 
> 和第二个字段包含字符：

冒号后面均没有具体说明。中英双语版正常（中英语共用样例）。

**Comment by happypeter** [comment]
感谢，回头会统一处理。或者您也可以直接发 PR

**Comment by Steven1677** [comment]
顺别一提，其实中文版内容有很多地方都是有问题的。问题和上面说的一样，造成的原因应该是中文和英文共享一个代码区块。还望您仔细检查。
另外，感谢您的翻译，让我的一名英语不太好的同学学习了相关知识。

Peter Wang <notifications@github.com>于2017年2月17日周五 下午6:32写道：

**Comment by happypeter** [comment]
thx
