### ISSUE TITLE
TLCL 是否会更新到第三版

### ISSUE THREAD

**Issue by SwiftSIQI** [billie66/TLCL#159]
发现 TLCL 已经在去年七月发布了第三版，你们会考虑更新内容至第三版么？

**Comment by Hexhu** [comment]
好问题，有时间就更新（误

P.S. 突然发现咱们这个 translation community 没在 [linuxcommand.org](http://linuxcommand.org/tlcl.php) 上出现，咱去交涉下看看...

**Comment by happypeter** [comment]
对，咱们这个应该加上的

**Comment by SwiftSIQI** [comment]
@happypeter @Hexhu 如果可以能带上我一起嘛，哈哈

**Comment by happypeter** [comment]
@SketchK  任何人都可以参与进来的，发 Pull Request 就可以了。

第三版暂时没有精力去翻译。

**Comment by happypeter** [comment]
no plan yet
