### ISSUE TITLE
Epub format seems not been allowed

### ISSUE THREAD

**Issue by liuhaoXD** [billie66/TLCL#165]
As william noted [here](http://linuxcommand.org/lc3_translations.php) 
> **Allowable Formats** - My publisher has exclusive rights to all formats except HTML and PDF. This means that translations must be distributed only in HTML and/or PDF. Distribution of printed copies is not permitted. The same goes for ePub, .mobi, etc.

Publishing it on GitBook which can export the book as epub or mobi format may have broken the license.

**Comment by happypeter** [comment]
removed
