### ISSUE TITLE
中英文双语版会释出ePub格式吗

### ISSUE THREAD

**Issue by shensven** [billie66/TLCL#167]
我尝试将[《中英文双语版-PDF-2015-01-16》](http://pan.baidu.com/s/1pJ4zcVL)导入到多看阅读，然后在Android手机或者iPad上阅读，如果直接阅读 pdf 格式，字体会非常小，但是排版完美。如果以文本视图阅读的话，可以自定义字体，但是排版会乱掉。
我尝试使用 Instapaper 阅读 [《中英文双语版-html》](http://billie66.github.io/TLCL/book/)，但是 Instapaper 不会随阅读进度的推进而更新我所收藏的List，Instapaper 和 Pocket 都不能作为最优阅读方案
能将 http://billie66.github.io/TLCL/book/ 上的内容发表到 GitBook 上吗，或者能释出ePub格式的中英文双语版吗

**Comment by happypeter** [comment]
暂时没有打算。
