### ISSUE TITLE
shell 环境一章有一个错误

### ISSUE THREAD

**Issue by robinhwang** [billie66/TLCL#17]
表格中，有
alias l.='ls -d .* --color=auto'   创建一个新命令，叫做'l.'，这个命令会显示所有以点开头的目录名。
这样的一行
但是经过我的环境Ubuntu 12.04LTS,这个命令因为单引号已经存在，正确的应是
alias l.='ls -d .\* --color=auto'
并不需要反斜杠

虽然问题挺小，但是还是会让人有点摸不着头脑，希望能改一下

**Comment by billie66** [comment]
这些代码块之前都直接用的 html 的格式， 后来用脚本生成 markdown 格式，却忘记把那些 html entities 转换为普通字符了。

**Comment by billie66** [comment]
This problem was fixed. 83bd4a524d90b
