### ISSUE TITLE
第30章 示例代码两处_EOF_未顶格

### ISSUE THREAD

**Issue by luanheart** [billie66/TLCL#177]
如下图
![one](http://img2.ciurl.cn/flashsale/upload/xinfotek_upload/2017/06/07/1496830095570894.jpg)
![two](http://img2.ciurl.cn/flashsale/upload/xinfotek_upload/2017/06/07/1496830068726502.jpg)

**Comment by billie66** [comment]
代码格式是根据原版文档写的，不需要改

**Comment by happypeter** [comment]
done
