### ISSUE TITLE
关于中文版

### ISSUE THREAD

**Issue by hzlpy** [billie66/TLCL#197]
你好，请问[中文版](http://billie66.github.io/TLCL/book/zh/chap07.html)的是没有了吗？之前还看到过。

**Comment by kyao233** [comment]
http://billie66.github.io/TLCL/book/

改地址了。

**Comment by awkj** [comment]
比较之前的版本，去掉了 中文版和英文版，保留了中英文并排版。

**Comment by happypeter** [comment]
exactly
