### ISSUE TITLE
吐槽下，很多地方逻辑性真的差，甚至比不上机翻

### ISSUE THREAD

**Issue by screamff** [billie66/TLCL#218]
To support this ability, the POSIX standards introduced a concept called a locale, which
could be adjusted to select the character set needed for a particular location. We can see the
language setting of our system using this command:
为了支持这种能力， POSIX 标准介绍了一种叫做 locale 的概念，其可以被调整，来为某个
特殊的区域，选择所需的字符集。通过使用下面这个命令，我们能够查看到我们系统的语言设
置

我是这么表达的：为了支持这种功能，posix标准引入了”locale“概念，它能针对不同地区选择合适的字符集。
我英文一般，读中文是为了一遍过，不用查字典，但是书中像这样的地方太多了，明明中文可以很简单准确的表达意思，但是却要像机翻一样去翻译，反而弄得本末倒置。

在此抛砖引玉，希望有大佬能润色一下。

**Comment by happypeter** [comment]
>introduced

翻译成了“介绍”，真的是很外行的。

**Comment by happypeter** [comment]
感谢批评。

**Comment by happypeter** [comment]
@screamff 能否发个 PR ？我 merge 进来。

**Comment by ghost** [comment]
'''
To support this ability, the POSIX standards introduced a concept called a locale, which
could be adjusted to select the character set needed for a particular location. We can see the
language setting of our system using this command:

'''
“为确保这种功能的实现，POSIX标准库引入了‘区域设置’的概念，它可以自适应选择特定区域的相应字符集。我们可以用以下命令设置我们的系统“

@_@ 处女翻  大神请轻喷

**Comment by Amigo007** [comment]
'''
To support this ability, the POSIX standards introduced a concept called a locale, which
could be adjusted to select the character set needed for a particular location. We can see the
language setting of our system using this command:

'''
“为确保这种功能的实现，POSIX标准库引入了‘区域设置’的概念，它可以自适应选择特定区域的相应字符集。我们可以用以下命令设置我们的系统“

@_@ 处女翻 大神请轻喷

**Comment by happypeter** [comment]
欢迎大家直接发 PR ， Pull Request
