### ISSUE TITLE
chapter10第637行翻译不妥

### ISSUE THREAD

**Issue by tzway** [billie66/TLCL#237]
> u+x,go=rw
> Add execute permission for the owner and set the permissions for the group and others to read and execute. Multiple specifications may be separated by `commas.
>  u+x,go=rw
>  给群组的主人和任意文件拥有者的人读写权限。如果群组的主人或全局之前已经有了执行的权限，他们将被移除。

> 

1、group owner不知道怎么翻译，我觉得应该翻译为所有组，此处作者把组？人格化？
2、besides在此处是除了（…之外）的意思

**Comment by tzway** [comment]
@kyao4 @Lix1993 @happypeter

**Comment by billie66** [comment]
@karsacui 这句翻译的不好，已经把你提交的 PR 合并了
