### ISSUE TITLE
pdf table

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#24]
leanpub can do this.
But I think it will be nice to do it with a script.

We already have all the tools available on ubuntu
http://happycasts.net/episodes?tag_id=4

**Comment by billie66** [comment]
kramdown 只支持比较简单的表格，若表格中某个单元格的内容比较长的话，不能够换行，无法处理这种情况

**Comment by billie66** [comment]
表格单元格内容分段

``` latex
\begin{tabular}{cc}
  boring cell content & \parbox[t]{5cm}{rather long par\\new par}
\end{tabular}
```

以上是一个有一行两列的表格，第二个单元格中的内容分两个自然段显示

不用以上那么麻烦，只要用 `\newline` 标志就可以在单元格中分段了，注意要指定单元格的长度，\newline 才能生效

``` latex
\begin{tabular}{c p{5cm}}
cell content & long content \newline  a new paragraph
\end{tabular}
```

**Comment by billie66** [comment]
长表格的内容不能完整展现出来，需要跨页显示，要用到 longtable 宏包

**Comment by billie66** [comment]
longtable 的使用

``` latex
\begin{center}
  \begin{longtable}[H]{ l p{10cm}}
     rows
  \caption{table 1:  commands}
  \end{longtable}
\end{center}
```

**Comment by billie66** [comment]
强调

``` latex
\emph{a new feature}
```

左双引号用两个倒引号 ` 表示，右双引号用两个 ' 表示

**Comment by billie66** [comment]
Removing prefix from table and figure captions in LaTeX

``` latex
\usepackage[labelformat=empty]{caption}
```

http://stackoverflow.com/questions/3842322/removing-prefix-from-figure-captions-in-latex

**Comment by billie66** [comment]
PDF 版本已经生成了，为了美观，对表格手动做了些调整。
