### ISSUE TITLE
第20章 锚点 一节中把 caret 翻译成“插入”似乎不妥

### ISSUE THREAD

**Issue by xjr7670** [billie66/TLCL#253]
> The caret and dollar sign characters are treated as anchors in regular expressions.

翻译

> 在正则表达式中，插入符号和美元符号被看作是锚点。

caret 直译为脱字符，据我所知国内大多叫控制字符，也没有看到过是叫“插入字符”的。无论用哪个，都应该会比直接翻译成 “插入符号和美元符号” 更加易懂

**Comment by billie66** [comment]
查了下必应词典，可以把 caret 翻译成 `插入符号`

为了方便理解，`caret and  dollar sign` 直接翻译成 `^ 和 $ 符号` 更为妥当
