### ISSUE TITLE
Chap20翻译小问题

### ISSUE THREAD

**Issue by YouDad** [billie66/TLCL#266]
我们可以看到，我们修订的表达式能成功地验证带有和不带有圆括号的数字，而拒绝那些格式 不正确的数字。
上面是原句,其中数字(number)其实在之前的语义应该是(电话)号码,所以以下翻译更加贴合原义:
我们可以看到，我们修订的表达式能成功地验证带有和不带有圆括号的号码，而拒绝那些格式不正确的号码。

**Comment by billie66** [comment]
您可以发送 PR
