### ISSUE TITLE
Introduction部分翻译求教

### ISSUE THREAD

**Issue by ghost** [billie66/TLCL#282]
“ In fact, one of the strongest reasons early adopters of Linux chose it over,say, Windows NT was the powerful command line interface that made the “difficult tasks possible.” ”  
您的翻译是：
事实上，很多人选择 Linux（而不是其他的系统，比如说 Windows NT）是因为其可以使“完成复杂的任务成为可能”的强大的命令行界面。

似乎作者要表达的意思是，Linux早期使用者选择Linux的原因是，它拥有和Windows NT一样强大的命令行界面，但他们不清楚的是，Linux的命令行工具大多继承自Unix。

因为根据日期推断，Linux真正达到可用状态，应该比Windows NT的发布时间要晚。

**Comment by happypeter** [comment]
您的理解是错误的。

choose a over b ，意思是” b 不行，所以选择 a“

**Comment by One2r** [comment]
“ In fact, one of the strongest reasons early adopters of Linux chose it over,say, Windows NT was the powerful command line interface that made the “difficult tasks possible.” ”
您的翻译是：
事实上，很多人选择 Linux（而不是其他的系统，比如说 Windows NT）是因为其可以使“完成复杂的任务成为可能”的强大的命令行界面。

我感觉，这句读起来还是怪怪的。

“he powerful command line interface” 应该是修饰 “Windows NT” 的吧。

所以我觉得，应该这样翻译：

事实上，很多人选择 Linux（而不是其他的系统，比如说有强大命令行界面的Windows NT）是因为其可以使“完成复杂的任务成为可能”。
