### ISSUE TITLE
更新的内容不能在网页中显示出来？

### ISSUE THREAD

**Issue by billie66** [billie66/TLCL#29]
这是因为 Jekyll 在把 markdown 文件转换为 html 文件时出现了错误， 一些 markdown   格式的文本书写错误，导致其不能被转换成 html 格式， 由于这些错误， github pages 就不能正常地创建，更新的内容就不能及时显示出来。那么怎么查找错误信息呢？ 那就需要在本地搭建 Jekyll 运行环境， 步骤如下：

```
gem install github-pages

jekyll server
```

通过上面两条命令，就可以很容易找到错误来源了。

**Comment by happypeter** [comment]
对，本地安装后是能爆出一些错来。不过也是麻烦。

我一般都是把 commit 弄小点，直接 push，出了问题 revert 一下就好了。
