### ISSUE TITLE
转换成 pdf 格式

### ISSUE THREAD

**Issue by billie66** [billie66/TLCL#36]

**Comment by happypeter** [comment]
很多边边角角的地方可能要自己编程加 latex 代码进去：http://happycasts.net/episodes/19

http://happycasts.net/episodes/20

**Comment by billie66** [comment]
kramdown 支持把 kramdown 格式的文本转换成 latex，然后由 latex 转换成 pdf。

**Comment by billie66** [comment]
把一个 kramdown 文件转换成 latex 文件

``` bash
kramdown -i kramdown -o latex input.md > output.tex
```

不过，有许多地方要处理，所以要知道一些 latex 的语法，才能得到正确的 latex 输出结果。

**Comment by happypeter** [comment]
设计目标：
- 项目名字可以叫 happypub，仿效 leanpub
- github GFM 书写，可以发布 html 和 pdf 两种形式，其他电子书格式我不关心
- 书的正文部分我就用我最熟悉的 GFM 来写，你别让我手动插入 html 甚至是 latex 代码
- 你可以给我规定内容如何分章节，章节如何命名，你才能帮我正常生成目录，这个我接受你的限制
- 页眉页脚封面这些地方，可以让我手动改 latex 代码，这个没问题

最终可以做成类似于 leanpub 那样的 web 应用，不过那是下一步的时了，暂时我们只要达到用命令或者手动编辑代码能够思路明晰的把一本 jekyll 的书，类似于 TLCL，顺利转换成 pdf 就可以了。

**Comment by billie66** [comment]
现在的 github GFM 已经支持 table 了，TLCL 中的表格直接使用 html 代码实现，现在需要更改为 GFM 格式的。先在本地测试一下，看看效果。

**Comment by billie66** [comment]
一个 latex book 模板，顺便学一下 latex 命令
https://github.com/amberj/latex-book-template

**Comment by billie66** [comment]
kramdown 会把表格转换成 latex 的 longtable 样式，所以需要安装 longtable

**Comment by happypeter** [comment]
TLCL 这本书有 table 等复杂的格式，所以这本咱们先放一放，先弄一个简单。

我的 LGCB 没有任何复杂格式，就有一张居中的图片。先把它搞定：https://github.com/happypeter/LGCB/issues/33
