### ISSUE TITLE
pdf 也可以很漂亮

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#37]
给加点 color 吧，类似：http://www.elasticsearch.org/content/uploads/2013/11/es_caseStudy_github.pdf

**Comment by billie66** [comment]
好呀，我研究一下

**Comment by billie66** [comment]
给第一标题，第二标题上了点儿色

**Comment by happypeter** [comment]
cool，注意体现 haoqicat 的商标色 teal
