### ISSUE TITLE
epub 格式

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#42]
https://ruby-china.org/topics/21831

很多人想要啊

**Comment by happypeter** [comment]
chrome 浏览器里安装 app 就可以读 epub 了，效果很好啊

**Comment by billie66** [comment]
好的，过两天我研究一下

**Comment by happypeter** [comment]
试了 gitbook 跟咱们的思路很接近了，直接就能出 epub pdf 各种格式。

**Comment by DelightRun** [comment]
应该写个Makefile，并且把源文件放在master分支下。
Python Sphinx作为文档生成工具非常好用，不过它用的是reStructedText而不是Markdown，这点很麻烦

**Comment by billie66** [comment]
这篇文章介绍如何通过 pandoc 把 progit 这本书的 markdown 格式转换成 epub 格式

http://johnmacfarlane.net/pandoc/epub.html

ubuntu 系统中已经安装了 pandoc 1.9，按照上面文章提供的方法，应该可以把 TLCL 转换成 epub 格式。

**Comment by billie66** [comment]
@DelightRun 把源文件放到 gh-pages 分支下，是为了直接浏览 html 网页格式 http://billie66.github.io/TLCL/ 如果放在 master 上面就看不到了

> Python Sphinx作为文档生成工具非常好用，不过它用的是reStructedText而不是Markdown，这点很麻烦

我比较熟悉 Markdown，希望有工具能把 markdown 直接转成 epub，正如 pandoc

**Comment by billie66** [comment]
转出了，放到安卓手机上用 ireader 看。表格和代码都因为屏幕太窄而变得难看。如果能把字体变小点，或者横屏看应该还好，但是找了一下 Ireader 的设置，改不了。

**Comment by billie66** [comment]
换了个英文阅读器 aldiko 字体可以调小，也可以横屏看，这次 代码 和 table 看上去效果就非常好了。

只是不支持中文。

qq 阅读：

代码有专门的字体支持挺好看，table 显示 shit，总而言之 shit

**Comment by billie66** [comment]
总之，就是要选择一款合适的阅读器。如果 aldiko 可以显示中文字体那么效果还是不错的。

**Comment by billie66** [comment]
这本书已经放到 gitbook 上面了，http://billie66.gitbooks.io/tlcl-cn/ ，但是封面不好看

**Comment by billie66** [comment]
https://github.com/GitbookIO/javascript 这是一本开源的 gitbook，封面比较好些，是自己做了一种封面图

这是 gitbook 关于封面的文档 http://help.gitbook.io/book/cover.html

**Comment by billie66** [comment]
按照 gitbook 的要求，自己做一张封面

**Comment by billie66** [comment]
添加了 cover 
- 加了两张图片
