### ISSUE TITLE
chap06 中的示例错误

### ISSUE THREAD

**Issue by diggzhang** [billie66/TLCL#45]
……
……
有时候在一个操作系统中，不只安装了可执行程序的一个版本。然而在桌面系统中，这并不普遍， 但在大型服务器中，却很平常。为了确定所给定的执行程序的准确位置，使用 which 命令：

[me@linuxbox ~]$ which **is**      <= 应该是**ls**
/bin/ls

……
……

**Comment by billie66** [comment]
这是 pdf 版本中的错误，网页版的已经更正过来了。pdf 版会稍后更新
