### ISSUE TITLE
gitbook.io

### ISSUE THREAD

**Issue by billie66** [billie66/TLCL#46]
转成的 pdf 很不好看，中文字体有问题。

epub 格式到手机上，存在 table 和 code 部分宽度太拥挤的问题，选择一个可以调解字体的 epub 阅读器，应该会好一些，目前还没有找到太合适的。

已经试过了 iReader QQ阅读 效果都不太好

**Comment by happypeter** [comment]
epub 看着还行，pdf 中文有问题，应该是他们的服务器上没装中文字库，不管了，他们的问题。
