### ISSUE TITLE
中英文双语版的 PDF

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#47]
慕课网上有小伙伴提了这个需求。其实我自己原来也想过，中英文对照，可以学英语，挺好的。

**Comment by billie66** [comment]
这个任务完成了 :smile: 

http://billie66.github.io/TLCL/index.html

**Comment by arjenhill** [comment]
在码农周刊上转载了，很火啊

**Comment by happypeter** [comment]
感谢！

**Comment by billie66** [comment]
非常感谢 :dancer:
