### ISSUE TITLE
需要一个从双语版，直接提取中文版的脚本

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#52]
现在每当有朋友贡献双语版的翻译，咱们需要手动去修改中文版。

未来的目标是：手动维护的版本只是双语版。中文版自动生成。

**Comment by billie66** [comment]
这个还是很必要的，之前写过一个脚本，但不精确，会把一些英文标题也过滤掉，现在完善一下

**Comment by billie66** [comment]
脚本名字为 getcn.rb ，运行命令 

```
ruby getcn.rb all
```

可以重新生成一遍这本书的中文版，也可以从单个文件中分离中文，以文件 chap01.md 为例，运行命令

```
ruby getcn.rb chap01
```
