### ISSUE TITLE
请问把markdown文件转换成一本电子书是怎么做到的？

### ISSUE THREAD

**Issue by jiajunhuang** [billie66/TLCL#59]
不仅仅是把一篇转换为pdf， 是把所有的转换成一本， 可以解答一下吗？

**Comment by billie66** [comment]
- 比较省事的方法是去 gitbook.io 网站创建一个账户，然后把 md 文件都传到 gitbook 网站上，gitbook 会帮你转出 pdf, epub, mobi 格式的电子书，不足之处是中文 pdf 字体不好看
- 相对复杂的做法是借助强大的 latex 排版工具，首先通过 kramdown 把 md 格式的文件转换成 latex 格式，然后再生成 pdf，这可以参考由 @happypeter 录制的关于 latex 的视频：
  
  http://happycasts.net/episodes/19
  
  latex 可以自定制包括字体在内的各种样式，因此能够生成特别漂亮的 pdf 文档，当然这需要花费一些时间

**Comment by jiajunhuang** [comment]
谢谢 ；p

**Comment by arjenhill** [comment]
billie66 好专业。

**Comment by billie66** [comment]
@jiayi2 就是生成 pdf 比较麻烦，不过有视频可以参考，还是比较容易上手操作
