### ISSUE TITLE
第四章：探究操作系统错误

### ISSUE THREAD

**Issue by h3l** [billie66/TLCL#67]
第四章：探究操作系统的表4.3

> > Page UP or b  向后翻滚一页
> > Page Down or space  向前翻动一页
> > UP Arrow    向前移动一行
> > Down Arrow  向后移动一行

翻译成

> > Page UP or b  向上翻滚一页
> > Page Down or space  向下翻滚一页
> > UP Arrow    向上翻滚一行
> > Down Arrow  向下翻滚一行

比较好吧
并且原翻译的page down 和 page up翻译反了把

**Comment by billie66** [comment]
Good，欢迎发 pull request

**Comment by h3l** [comment]
已提交

**Comment by billie66** [comment]
已经 merge 了，谢谢
