### ISSUE TITLE
Links of PDF Version on http://billie66.github.io/TLCL/ return 404 Not Found

### ISSUE THREAD

**Issue by lzdhlsc** [billie66/TLCL#77]
Links of PDF Version on http://billie66.github.io/TLCL/ return 404 Not Found:
http://media.happycasts.net/tlcl-en-cn.pdf
http://media.happycasts.net/tlcl-cn.pdf

**Comment by happypeter** [comment]
这个是我的错，服务器出问题了，把这两个文件给不小心删了。

我马上着手恢复。

**Comment by happypeter** [comment]
@billie66 给重新生产一份吧

**Comment by billie66** [comment]
The pdf had been updated to the most recent version.
