### ISSUE TITLE
移动 pdf 的托管位置

### ISSUE THREAD

**Issue by happypeter** [billie66/TLCL#98]
http://billie66.github.io/TLCL/ 

上的书的 pdf 目前放在 media.happycasts.net 上，现在这个站点要下线了。还是把这些 pdf 放到 selfstore 上吧，价格设置成0就行了。

**Comment by billie66** [comment]
上传到 SelfStore 了， 地址： https://selfstore.io/products/347

**Comment by happypeter** [comment]
cool

**Comment by billie66** [comment]
从 selfstore 上撤下来了，那放到百度云上

**Comment by boyang0830** [comment]
```js
alert("hello")
```
